userland: add pkg-configs for egl and glesv2
Without this many packages complaing for missing egl/gles during configure.
egl.pc includes path ${incdir}/interface/vcos/pthreads to fix

| In file included from /home/superandy/tmp/oe-core-glibc/sysroots/raspberrypi/usr/include/interface/vcos/vcos_assert.h:149:0,
|                  from /home/superandy/tmp/oe-core-glibc/sysroots/raspberrypi/usr/include/interface/vcos/vcos.h:114,
|                  from /home/superandy/tmp/oe-core-glibc/sysroots/raspberrypi/usr/include/interface/vmcs_host/vc_dispmanx.h:33,
|                  from /home/superandy/tmp/oe-core-glibc/sysroots/raspberrypi/usr/include/EGL/eglplatform.h:110,
|                  from /home/superandy/tmp/oe-core-glibc/sysroots/raspberrypi/usr/include/EGL/egl.h:36,
|                  from ../src/gl-state-egl.h:26,
|                  from ../src/main.cpp:48:
| /home/superandy/tmp/oe-core-glibc/sysroots/raspberrypi/usr/include/interface/vcos/vcos_types.h:38:33: fatal error: vcos_platform_types.h: No such file or directory
|  #include "vcos_platform_types.h"
|                                  ^
| compilation terminated.

Signed-off-by: Andreas Müller <schnitzeltony@googlemail.com>